version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - local-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    links:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - local-net

  api:
    container_name: "api"

    build: ./AntiPlagiat
    ports:
      - "8080:8080"
    volumes:
      - ./AntiPlagiat:/usr/src/server
    networks:
      - local-net

  frontend:
    build: ./Antiplagiat-front
    ports:
      - 80:80

volumes:
  esdata:
    driver: local

networks:
  local-net:
    driver: bridge
